# namePrefix: test1-
resources:
- namespace.yaml
- ../base
namespace: dev
patchesStrategicMerge:
- replica_count.yaml
- cpu_count.yaml
patchesJson6902:
- path: ingress_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: eimmo-ingress
    version: v1beta1
images:
- name: eimmo-backend-image
  newName: tttt
  newTag: 1553b0275bfbe156b05df0afc06a2c8d96482753
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
